name: NX CD Test
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: checkout nx
        uses: nrwl/nx-set-shas@v2

      - name: install Deps
        working-directory: ./apps/todos
        run: yarn install

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx build todos
